# GENERATED BY PYTHON - CONTROLED BY SPREADSHEET
# Increase card count related scores

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Validate number of copies
scoreboard players operation #copies deck.process_card < 3 number

# Increment rarity counts
scoreboard players operation cards.total deck.analysis += #copies deck.process_card
scoreboard players operation cards.rare deck.analysis += #copies deck.process_card

# Increment card type counts
scoreboard players operation cards.spellbind deck.analysis += #copies deck.process_card
