# GENERATED BY PYTHON - CONTROLED BY SPREADSHEET
# Call analyze function(s) and validation

## CONSTRAINTS
#   AS/AT profile node

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Call analyze based on number of copies
execute if score #copies deck.process_card matches 1.. run function exigence:cards/mind_of_divinity/analyze
execute if score #copies deck.process_card matches 2.. run function exigence:cards/mind_of_divinity/analyze
execute if score #copies deck.process_card matches 3.. run function exigence:cards/mind_of_divinity/analyze
execute if score #copies deck.process_card matches 4.. run function exigence:deck/process/private/error/too_many_copies_m {display_name:'Mind of Divinity',rarity_color:'blue'}

# Call analyze_b based on number of copies
execute if score #copies deck.process_card matches 1.. run function exigence:cards/mind_of_divinity/analyze_b
execute if score #copies deck.process_card matches 2.. run function exigence:cards/mind_of_divinity/analyze_b
execute if score #copies deck.process_card matches 3.. run function exigence:cards/mind_of_divinity/analyze_b

# Increment card totals
scoreboard players operation #copies deck.process_card < 3 number
scoreboard players operation cards.total deck.analysis += #copies deck.process_card
scoreboard players operation cards.rare deck.analysis += #copies deck.process_card
