# GENERATED BY PYTHON - CONTROLED BY SPREADSHEET
# Call analyze function(s) and validation

## CONSTRAINTS
#   AS/AT profile node

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Get cost and validate
function exigence:cards/get_cost {card_name:'blessed_harvest'}

# Only add validation checks for resources actually used by this card
execute if score aqua.cost game.resources > resource.aqua.max deck.analysis run function exigence:deck/process/private/error/cost_too_great_m {display_name:'Blessed Harvest',resource:'aqua',resource_color:'aqua',rarity_color:'green'}

# Call analyze based on number of copies
execute if score #copies deck.process_card matches 1.. run function exigence:cards/blessed_harvest/analyze
execute if score #copies deck.process_card matches 2.. run function exigence:cards/blessed_harvest/analyze
execute if score #copies deck.process_card matches 3.. run function exigence:cards/blessed_harvest/analyze
execute if score #copies deck.process_card matches 4.. run function exigence:deck/process/private/error/too_many_copies_m {display_name:'Blessed Harvest',rarity_color:'green'}

# Increment card totals
scoreboard players operation #copies deck.process_card < 3 number
scoreboard players operation cards.total deck.analysis += #copies deck.process_card
scoreboard players operation cards.uncommon deck.analysis += #copies deck.process_card
