# GENERATED BY PYTHON - CONTROLED BY SPREADSHEET
# Call analyze function(s) and validation

## CONSTRAINTS
#   AS/AT profile node

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Call analyze based on number of copies
execute if score #copies deck.process_card matches 1.. run function exigence:cards/eyes_on_the_prize/analyze
execute if score #copies deck.process_card matches 2.. run function exigence:cards/eyes_on_the_prize/analyze
execute if score #copies deck.process_card matches 3.. run function exigence:cards/eyes_on_the_prize/analyze
execute if score #copies deck.process_card matches 4.. run function exigence:deck/process/private/error/too_many_copies_m {display_name:'Eyes on the Prize',rarity_color:'green'}

# Increment card totals
scoreboard players operation #copies deck.process_card < 3 number
scoreboard players operation cards.total deck.analysis += #copies deck.process_card
scoreboard players operation cards.uncommon deck.analysis += #copies deck.process_card
