# GENERATED BY PYTHON - CONTROLED BY SPREADSHEET
# Call analyze function(s) and validation

## CONSTRAINTS
#   AS/AT profile node

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Call analyze based on number of copies
execute if score #copies deck.process_card matches 1.. run function exigence:cards/dev_no_menace/analyze
execute if score #copies deck.process_card matches 2.. run function exigence:deck/process/private/error/too_many_copies_legendary {display_name:'Dev No Menace',rarity_color:'red'}

# Analyze card counts:
function exigence:cards/dev_no_menace/analyze/card_counts