# GENERATED BY PYTHON - CONTROLED BY SPREADSHEET
# Call analyze function(s) and validation

## CONSTRAINTS
#   AS/AT profile node

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Call analyze based on number of copies
execute if score #copies deck.process_card matches 1.. run function exigence:cards/spell_scroll/analyze
execute if score #copies deck.process_card matches 2.. run function exigence:cards/spell_scroll/analyze
execute if score #copies deck.process_card matches 3.. run function exigence:cards/spell_scroll/analyze
execute if score #copies deck.process_card matches 4.. run function exigence:deck/process/private/error/too_many_copies_m {display_name:'Spell Scroll',rarity_color:'green'}

# Analyze card counts:
function exigence:cards/spell_scroll/analyze/card_counts