# GENERATED BY PYTHON - CONTROLED BY SPREADSHEET
# Call analyze function(s) and validation

## CONSTRAINTS
#   AS/AT profile node

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Get cost and validate
function exigence:cards/get_cost {card_name:'salvage'}

# Only add validation checks for resources actually used by this card
execute if score green.cost game.resources > resource.green.max deck.analysis run function exigence:deck/process/private/error/cost_too_great_m {display_name:'Salvage',resource:'green',resource_color:'dark_green',rarity_color:'green'}

# Call analyze based on number of copies
execute if score #copies deck.process_card matches 1.. run function exigence:cards/salvage/analyze
execute if score #copies deck.process_card matches 2.. run function exigence:cards/salvage/analyze
execute if score #copies deck.process_card matches 3.. run function exigence:cards/salvage/analyze
execute if score #copies deck.process_card matches 4.. run function exigence:deck/process/private/error/too_many_copies_m {display_name:'Salvage',rarity_color:'green'}

# Analyze card counts:
function exigence:cards/salvage/analyze/card_counts