# GENERATED BY PYTHON - CONTROLED BY SPREADSHEET
# Call analyze function(s) and validation

## CONSTRAINTS
#   AS/AT profile node

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Get cost and validate
function exigence:cards/get_cost {card_name:'concordance'}

# Only add validation checks for resources actually used by this card
execute if score aqua.cost game.resources > resource.aqua.max deck.analysis run function exigence:deck/process/private/error/cost_too_great_m {display_name:'Concordance',resource:'aqua',resource_color:'aqua',rarity_color:'light_purple'}

# Call analyze based on number of copies
execute if score #copies deck.process_card matches 1.. run function exigence:cards/concordance/analyze
execute if score #copies deck.process_card matches 2.. run function exigence:deck/process/private/error/too_many_copies_legendary {display_name:'Concordance',rarity_color:'light_purple'}

# Analyze card counts:
function exigence:cards/concordance/analyze/card_counts