# GENERATED BY PYTHON - CONTROLED BY SPREADSHEET
# Call analyze function(s) and validation

## CONSTRAINTS
#   AS/AT profile node

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Get cost and validate
function exigence:cards/get_cost {card_name:'entangle'}

# Only add validation checks for resources actually used by this card
execute if score green.cost game.resources > resource.green.max deck.analysis run function exigence:deck/process/private/error/cost_too_great_m {display_name:'Entangle',resource:'green',resource_color:'dark_green',rarity_color:'light_purple'}

# Call analyze based on number of copies
execute if score #copies deck.process_card matches 1.. run function exigence:cards/entangle/analyze
execute if score #copies deck.process_card matches 2.. run function exigence:deck/process/private/error/too_many_copies_legendary {display_name:'Entangle',rarity_color:'light_purple'}

# Increment card totals
scoreboard players operation #copies deck.process_card < 1 number
scoreboard players operation cards.total deck.analysis += #copies deck.process_card
scoreboard players operation cards.legendary deck.analysis += #copies deck.process_card
