# GENERATED BY PYTHON - CONTROLED BY SPREADSHEET
# Call analyze function(s) and validation

## CONSTRAINTS
#   AS/AT profile node

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Get cost and validate
function exigence:cards/get_cost {card_name:'synaptic_shock'}

# Only add validation checks for resources actually used by this card
execute if score red.cost game.resources > resource.red.max deck.analysis run function exigence:deck/process/private/error/cost_too_great_m {display_name:'Synaptic Shock',resource:'red',resource_color:'dark_red',rarity_color:'light_purple'}

# Call analyze based on number of copies
execute if score #copies deck.process_card matches 1.. run function exigence:cards/synaptic_shock/analyze
execute if score #copies deck.process_card matches 2.. run function exigence:deck/process/private/error/too_many_copies_legendary {display_name:'Synaptic Shock',rarity_color:'light_purple'}

# Analyze card counts:
function exigence:cards/synaptic_shock/analyze/card_counts