# GENERATED BY PYTHON - CONTROLED BY SPREADSHEET
# Call analyze function(s) and validation

## CONSTRAINTS
#   AS/AT profile node

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Call analyze based on number of copies
execute if score #copies deck.process_card matches 1.. run function exigence:cards/dev_freesources/analyze
execute if score #copies deck.process_card matches 2.. run function exigence:deck/process/private/error/too_many_copies_legendary {display_name:'Dev Freesources',rarity_color:'red'}

# Call analyze_b based on number of copies
execute if score #copies deck.process_card matches 1.. run function exigence:cards/dev_freesources/analyze_b {copy:1}

# Analyze card counts:
function exigence:cards/dev_freesources/analyze/card_counts