# GENERATED BY PYTHON - CONTROLED BY SPREADSHEET
# Call analyze function(s) and validation

## CONSTRAINTS
#   AS/AT profile node

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Get cost and validate
function exigence:cards/get_cost {card_name:'commune_with_nature'}

# Only add validation checks for resources actually used by this card
execute if score green.cost game.resources > resource.green.max deck.analysis run function exigence:deck/process/private/error/cost_too_great_m {display_name:'Commune with Nature',resource:'green',resource_color:'dark_green',rarity_color:'green'}

# Call analyze based on number of copies
execute if score #copies deck.process_card matches 1.. run function exigence:cards/commune_with_nature/analyze
execute if score #copies deck.process_card matches 2.. run function exigence:cards/commune_with_nature/analyze
execute if score #copies deck.process_card matches 3.. run function exigence:cards/commune_with_nature/analyze
execute if score #copies deck.process_card matches 4.. run function exigence:deck/process/private/error/too_many_copies_m {display_name:'Commune with Nature',rarity_color:'green'}

# Increment card totals
scoreboard players operation #copies deck.process_card < 3 number
scoreboard players operation cards.total deck.analysis += #copies deck.process_card
scoreboard players operation cards.uncommon deck.analysis += #copies deck.process_card
